import Head from 'next/head'
import List from "./components/List"
import Pie from "./components/Pie"

export default function Home() {
  return (
    <>
      <Head>
        <title>Otto Dev Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='m-5'>
          <h1>Public Issues</h1>
          <div className='grid grid-cols-2 gap-2'>
            <div className='col-span-1'>
              <List />
            </div>
            <div>
              <Pie />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
