import Head from 'next/head'
import List from "./components/List"

export default function Home() {
  return (
        <>
          <Head>
            <title>Otto Dev Task</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
            <List />
          </main>
        </>
  )
}
